### ISSUE TITLE
Breaking?

### ISSUE THREAD

**Issue by shuwens** [lkatalin/Categorization#2]
I tried `python main.py samples/all_dots.dot` and it doesn't work. It is breaking? And I think you also need to mention which version of python are you using.

logs
```
(.venv) [~/git/Categorization]-[master↓]── - python main.py samples/all_dots.dot
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    tracelist = extract_traces(infile)
  File "/home/jethros/git/Categorization/extract_traces.py", line 18, in extract_traces
    traceObj = make_trace("".join(buff))
  File "/home/jethros/git/Categorization/objectify.py", line 52, in make_trace
    t = Trace(trace)
  File "/home/jethros/git/Categorization/objectify.py", line 48, in __init__
    self.hashval = hashval(self)
  File "/home/jethros/git/Categorization/group_traces.py", line 44, in hashval
    lst = depth_first_traversal(trace)
  File "/home/jethros/git/Categorization/group_traces.py", line 28, in depth_first_traversal
    with Timer() as t:
TypeError: Timer takes at least 2 arguments
```

**Comment by lkatalin** [comment]
Fixed this last week; it was one line of code I had accidentally left in for debugging, which required a Timer module. This module is not required and the code no longer has this issue.
