### ISSUE TITLE
local variable 'src_str' referenced before assignment

### ISSUE THREAD

**Issue by shuwens** [lkatalin/Categorization#9]
It is a bug hidden by not indented code. 

To reproduce, indent `make_dag.py` and run `python json_dag.py samples/0ecb71d7-0105-4423-8459-2a0eb641a4b6.json | python main.py`.
```
(.venv) [~/workspace/Categorization]-[master↓]── - python json_dag.py samples/0ecb71d7-0105-4423-8459-2a0eb641a4b6.json | python main.py
id_str: ae10fbb8536eb4c1fa2938d04d4e466aa
current root list: ['ae10fbb8536eb4c1fa2938d04d4e466aa']
id_str: a9889cc223cb54c0192f749a0151b5d57
current root list: ['ae10fbb8536eb4c1fa2938d04d4e466aa', 'a9889cc223cb54c0192f749a0151b5d57']
id_str: ad09455c56efc4225b311fd9d6225e355
current root list: ['ae10fbb8536eb4c1fa2938d04d4e466aa', 'a9889cc223cb54c0192f749a0151b5d57', 'ad09455c56efc4225b311fd9d6225e355']
id_str: ad8eaf330c3f148a1859ec2ac637be38b
current root list: ['ae10fbb8536eb4c1fa2938d04d4e466aa', 'a9889cc223cb54c0192f749a0151b5d57', 'ad09455c56efc4225b311fd9d6225e355', 'ad8eaf330c3f148a1859ec2ac637be38b']
dst str: a9889cc223cb54c0192f749a0151b5d57
Traceback (most recent call last):
  File "main.py", line 23, in <module>
    tracelist = extract_traces(sys.stdin.readlines())
  File "/home/jethros/workspace/Categorization/extract_traces.py", line 18, in extract_traces
    traceObj = make_trace("".join(buff))
  File "/home/jethros/workspace/Categorization/objectify.py", line 52, in make_trace
    t = Trace(trace)
  File "/home/jethros/workspace/Categorization/objectify.py", line 47, in __init__
    self.dag = dag(self)
  File "/home/jethros/workspace/Categorization/make_dag.py", line 51, in dag
    srcnode = id_to_obj[src_str]
UnboundLocalError: local variable 'src_str' referenced before assignment
```

**Comment by lkatalin** [comment]
Not a bug, the automatic indentation was incorrect. I added an extra space between the lines it was confused about, so it should be okay now even if automatically indented.
